msg
[/tiago_autonomous_navigation/set_logger_level]: new Service instance
Recording to 'S3W2_2.bag'.
Less than 5 x 1G of space free on disk with 'S3W2_2.bag.active'.
Tuck arm...
Started controllers: imu_sensor_controller
"Started controllers: joint_state_controller, torso_controller, head_controller, arm_controller, mobile_base_controller"
Started controllers: hand_controller
Started controllers: force_torque_sensor_controller
Controller Spawner: Loaded controllers: arm_velocity_trajectory_controller
Waiting for move_base action server...
connecting to ella-HP-ZBook-Studio-G5 41065
connecting to ella-HP-ZBook-Studio-G5 41065
connecting to ella-HP-ZBook-Studio-G5 41065
Connected to move_base action server.
"Sending goal 1 to move_base: x=-2.5, y=0.0"
"Transitioning to ACTIVE (from WAITING_FOR_GOAL_ACK, goal: /tiago_autonomous_navigation-1-1718027220.233)"
Got a transition callback on a goal handle that we're not tracking
Navigating to waypoint 1...
Less than 5 x 1G of space free on disk with 'S3W2_2.bag.active'.
Arm tucked.
Motion played successfully.
"Transitioning to WAITING_FOR_RESULT (from ACTIVE, goal: /tiago_autonomous_navigation-1-1718027220.233)"
"Transitioning to DONE (from WAITING_FOR_RESULT, goal: /tiago_autonomous_navigation-1-1718027220.233)"
GOAL Reached!
Reached waypoint 1
"Sending goal 2 to move_base: x=-4.0, y=-5.5"
Navigating to waypoint 2...
"Transitioning to ACTIVE (from WAITING_FOR_GOAL_ACK, goal: /tiago_autonomous_navigation-2-1718027251.658)"
Failed to get a plan.
Clearing both costmaps outside a square (3.00m) large centered on the robot.
Clearing both costmaps outside a square (1.50m) large centered on the robot.
Rotate recovery behavior started.
Less than 5 x 1G of space free on disk with 'S3W2_2.bag.active'.
Failed to get a plan.
Aborting because a valid plan could not be found. Even after executing all recovery behaviors
"Transitioning to WAITING_FOR_RESULT (from ACTIVE, goal: /tiago_autonomous_navigation-2-1718027251.658)"
"Transitioning to DONE (from WAITING_FOR_RESULT, goal: /tiago_autonomous_navigation-2-1718027251.658)"
Failed to reach waypoint 2
